<?php

/**
 * Implements hook_enable().
 */
function sitenow_people_enable() {
  $item = array(
    'link_path' => drupal_get_normal_path('people'),
    'link_title' => 'People',
    'menu_name' => 'main-menu',
  );
  
  menu_link_save($item);
  menu_cache_clear_all();
  
  variable_set('test', 'enabled');
}

/**
 * Implements hook_disable().
 */
function sitenow_people_disable() {
  variable_set('test', 'disabled');
}