<?php
/**
 * @file
 * Code for the SiteNow People feature.
 */

include_once 'sitenow_people.features.inc';

drupal_add_css(drupal_get_path('module', 'sitenow_people') . '/css/sitenow_people.css');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_people_form_ctools_entity_field_content_type_formatter_styles_alter(&$form, &$form_state, $form_id) {
  // We want to act only on the Photo (field_person_image) field.
  if ($form['ctools_field_list']['#value'][0]['field_name'] == 'field_person_image') {
    // Restrict the view mode options to the entity view modes correspinding to
    // the manual crop options available for this field.
    $form['file_view_mode']['#options'] = array(
      'person_small_100x100' => 'Person Small (100x100)',
      'person_large_220x220' => 'Person Large (220x220)',
    );
  }
}
