<?php
/**
 * @file
 * Code for the SiteNow People feature.
 */

include_once 'sitenow_people.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_people_form_ctools_entity_field_content_type_formatter_styles_alter(&$form, &$form_state, $form_id) {
  // We want to act only on the Photo (field_person_image) field.
  if ($form['ctools_field_list']['#value'][0]['field_name'] == 'field_person_image') {
    // Restrict the view mode options to the entity view modes correspinding to
    // the manual crop options available for this field.
    $form['file_view_mode']['#options'] = array(
      'people_table' => 'Person Small (100x67)',
      'people_grid' => 'Person Large (500x333)',
    );
  }
}
